import = [
	"~/.config/alacritty/themes/kanagawa_wave.toml"
]
general.live_config_reload = true
[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 25
y = 20

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"
