# Forma del cursore (beam = barra verticale, block = blocco, underline = sottolineato)
cursor_shape beam

# Intervallo di lampeggiamento (in secondi). 0 per lasciarlo fisso.
cursor_blink_interval 0.5

# --- EFFETTO SCIA (CURSORE FLUIDO) ---
# Quanti passi di scia deve lasciare il cursore (più è alto, più la scia è lunga)
cursor_trail 3

# Gestisce il decadimento della scia (il primo valore è il tempo di inizio, il secondo la durata)
cursor_trail_decay 0.1 0.4

# Spessore minimo della scia del cursore
cursor_trail_start_threshold 2

background_opacity 0.8

font_size 12.0
font_family      CaskaydiaCove Nerd Font
bold_font        CaskaydiaCove Nerd Font Bold
italic_font      CaskaydiaCove Nerd Font Italic
bold_italic_font CaskaydiaCove Nerd Font Bold Italic

# BEGIN_KITTY_THEME
# zenbones_dark
include current-theme.conf
# END_KITTY_THEME
