# ~/.config/wayle/themes/red.toml

bg = "#1e1414"
surface = "#2c1e1e"
elevated = "#3c2a2a"

fg = "#f2e5bc"
fg_muted = "#8c7a7a"

primary = "#e05f5f"

red = "#e05f5f"
yellow = "#d8a657"
green = "#a9b665"
blue = "#7daea3"
