[styling.palette]
primary = "#ffb4a9"
fg = "#ffb4a9"
fg-muted = "#e7bdb6"
elevated = "#1a1110"

[modules.dashboard]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#ffb4a9"
icon-bg-color = "#ffb4a9"

[modules.cava]
container-bg-color = "#1a1110"
icon-color = "#ffb4a9"
bar-color = "#ffb4a9"

[modules.hyprland-workspaces]
container-bg-color = "#1a1110"
active-color = "#ffb4a9"
active-bg-color = "#ffb4a9"
active-fg-color = "#1a1110"
inactive-color = "#ffb4a9"
inactive-bg-color = "#1a1110"

[modules.systray]
button-bg-color = "#1a1110"

[modules.clock]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#1a1110"
icon-bg-color = "#ffb4a9"

[modules.battery]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#ffb4a9"
icon-bg-color = "#ffb4a9"

[modules.bluetooth]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#ffb4a9"
icon-bg-color = "#ffb4a9"

[modules.network]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#ffb4a9"
icon-bg-color = "#ffb4a9"

[modules.volume]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#ffb4a9"
icon-bg-color = "#ffb4a9"

[modules.microphone]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#1a1110"
icon-bg-color = "#ffb4a9"

[modules.media]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#ffb4a9"
icon-bg-color = "#ffb4a9"

[modules.notification]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#ffb4a9"
icon-bg-color = "#ffb4a9"

[modules.window-title]
label-color = "#ffb4a9"
button-bg-color = "#1a1110"
icon-color = "#1a1110"
icon-bg-color = "#ffb4a9"
