# Generato automaticamente da Matugen

$bg = rgba(1a1110ff)
$surface_container = rgba(32282699)
$fg = rgba(f1dedcff)
$fg_muted = rgba(d8c2becc)

$accent = rgba(ffb4a9ff)
$accent_alpha = rgba(ffb4a966)

$check_color = rgba(dec38ccc)
$fail_color = rgba(ffb4abcc)
