[SupersonicTheme]
Name = "Matugen integration for Supersonic"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "{{ colors.background.default.hex }}"
ListHeader = "{{ colors.surface_container.default.hex }}"
PageHeader = "{{ colors.surface_container.default.hex }}"
Background = "{{ colors.surface_container.default.hex }}"
Button = "{{ colors.surface_variant.default.hex }}"
DisabledButton = "{{ colors.surface_container_high.default.hex }}"
Disabled = "{{ colors.on_surface_variant.default.hex }}"
Error = "{{ colors.error.default.hex }}"
Focus = "{{ colors.surface_container_highest.default.hex }}"
Foreground = "{{ colors.on_background.default.hex }}"
ForegroundOnError = "{{ colors.on_error.default.hex }}"
ForegroundOnPrimary = "#303446FF"
ForegroundOnSuccess = "#303446FF"
ForegroundOnWarning = "#303446FF"
HeaderBackground = "{{ colors.outline.default.hex }}"
Hover = "{{ colors.on_primary.default.hex }}"
Hyperlink = "{{ colors.on_surface.default.hex }}"
InputBackground = "{{ colors.surface_container_low.default.hex }}"
InputBorder = "{{ colors.surface_container.default.hex }}"
MenuBackground = "{{ colors.surface_container.default.hex }}"
OverlayBackground = "{{ colors.surface_container.default.hex }}"
Placeholder = "{{ colors.on_surface_variant.default.hex }}"
Pressed = "#41455966"
Primary = "{{ colors.primary.default.hex }}"
ScrollBar = "#292C3C99"
Selection = "{{ colors.primary_container.default.hex }}"
Separator = "#232634FF"
Success = "#A6D189FF"
Warning = "#E5C890FF"
